# type: ignore
import os
from dataclasses import dataclass
from pathlib import Path

import torch
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING, OmegaConf

from mimo.models import get_model
from mimo.data import get_data, complex_to_real
from mimo.losses import add_noise_to_data, score_training_loss


@dataclass
class TrainConfig:
    arch: str = "ncsnv2"
    save_dir: Path = MISSING
    device: str = "cuda"

    # Data
    train_data: Path = MISSING
    val_data: Path = MISSING

    # Training
    batch_size: int = 32
    num_steps: int = 100000
    lr: float = 0.0001
    eps: float = 0.001
    # Verbosity
    loss_verbose: int = 100
    save_verbose: int = 1000
    val_batch_size: int = 100

    # Noise schedule
    num_noise_levels: int = 2311
    max_noise_level: float = 39.15
    noise_step_factor: float = 0.995
    noise_distribution: str = "geometric"

    def __post_init__(self):
        if not self.train_data.is_file():
            raise ValueError("Training data file must exist and be generated by mimo.cdl!")

        if not self.val_data.is_file():
            raise ValueError("Validation data file must exist and be generated by mimo.cdl!")


cs = ConfigStore.instance()
cs.store(name="train", node=TrainConfig)


@hydra.main(version_base=None, config_name="train")
def main(structured_cfg: TrainConfig) -> None:
    cfg: TrainConfig = OmegaConf.to_object(structured_cfg)  # type: ignore[reportAssignmentType]
    os.makedirs(cfg.save_dir, exist_ok=True)

    # Get data
    train_data, train_config = get_data(cfg.train_data)
    train_dataset = TensorDataset(train_data)
    train_dataloader = DataLoader(train_dataset, batch_size=cfg.batch_size, shuffle=True)

    val_data, _ = get_data(cfg.val_data)
    val_dataset = TensorDataset(val_data)
    val_dataloader = DataLoader(val_dataset, batch_size=cfg.val_batch_size, shuffle=True)

    # Instantiate model
    model = get_model(
        cfg.arch,
        cfg.max_noise_level,
        cfg.num_noise_levels,
        cfg.noise_step_factor,
        num_rx=train_config.num_rx,
        num_tx=train_config.num_tx,
    ).to(cfg.device)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Model has {total_params} weights!")

    # Instantiate optimizer
    optimizer = Adam(model.parameters(), lr=cfg.lr, eps=cfg.eps)

    # Training loop
    trailing_loss = 0.0
    train_loss_log, val_loss_log = [], []
    for step in range(cfg.num_steps):
        model.train()
        batch = next(iter(train_dataloader))[0]
        batch = batch.to(cfg.device)

        # Pick noise levels uniformly at random
        stddev_idx = torch.randint(0, len(model.sigmas), (len(batch),), device=cfg.device)
        stddev = model.sigmas[stddev_idx]
        batch = complex_to_real(batch)
        batch_noisy, noise = add_noise_to_data(batch, stddev)

        # Pass through model
        output = model(batch_noisy, stddev_idx)
        # Compute the loss function
        loss = score_training_loss(output, noise, stddev)

        trailing_loss = loss.item() if step == 0 else trailing_loss * 0.99 + loss.item() * 0.01
        train_loss_log.append(trailing_loss)

        # Update the model
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Validate and sample from the model
        if (step + 1) % cfg.loss_verbose == 0:
            model.eval()
            with torch.inference_mode():
                # Get a batch of validation samples
                val_samples = next(iter(val_dataloader))[0]
                val_samples = val_samples.to(cfg.device)

                # Compute validation loss
                stddev_idx = torch.randint(
                    0, len(model.sigmas), (len(val_samples),), device=cfg.device
                )
                stddev = model.sigmas[stddev_idx]
                val_samples = complex_to_real(val_samples)
                val_samples_noisy, noise = add_noise_to_data(val_samples, stddev)

                # Pass through model
                output = model(val_samples_noisy, stddev_idx)
                # Compute the loss function
                val_loss = score_training_loss(output, noise, stddev)
                print(
                    f"Step {step}, Train Loss {trailing_loss:.2f}, Val. Loss {val_loss.item():.2f}"
                )
                val_loss_log.append(val_loss)

                # Save model weights to disk
                if (step + 1) % cfg.save_verbose == 0 or (step + 1) == cfg.num_steps:
                    torch.save(
                        {
                            "model_state_dict": model.state_dict(),
                            "optim_state_dict": optimizer.state_dict(),
                            "cfg": OmegaConf.to_container(structured_cfg, resolve=True),
                            "train_loss_log": train_loss_log,
                            "val_loss_log": val_loss_log,
                        },
                        cfg.save_dir / f"weights_step{step}.pt",
                    )


if __name__ == "__main__":
    main()
